version: "3"
services:
    db:
        build:
            context: requirements/mariadb/.
        volumes:
            - db_data:/var/lib/mysql
        container_name: database
        restart: always
        ports:
            - '3306:3306'
        env_file: .env
    wordpress:
        depends_on:
            - db
        build:
            context: requirements/wordpress/.
        container_name: wordpress
        ports:
            - "8080:80"
        volumes:
            - wp_volume:/var/www/html/
        restart: always
        env_file: .env
    nginx:
        depends_on:
            - wordpress
        restart: always
        build:
            context: requirements/nginx/.
        container_name: nginx
        ports:
            - '443:443'
        volumes:
            - wp_volume:/data
        stdin_open: true
        tty: true
        env_file: .env

volumes:
    db_data: {}
    wp_volume: {}
