version: "3"
services:
    db:
        build:
            context: requirements/mariadb/.
            args:
                MYSQL_USER: ${MYSQL_USER}
                MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - db_volume:/var/lib/mysql
        container_name: database
        restart: always
        env_file: .env
        networks:
            - mynetwork
    wordpress:
        depends_on:
            - db
        build:
            context: requirements/wordpress/.
        container_name: wordpress
        volumes:
            - wp_volume:/var/www/html/
        restart: always
        env_file: .env
        networks:
            - mynetwork
    nginx:
        depends_on:
            - wordpress
        restart: always
        build:
            context: requirements/nginx/.
        container_name: nginx
        ports:
            - '443:443'
        volumes:
            - wp_volume:/var/www/html/
        stdin_open: true
        tty: true
        env_file: .env
        networks:
            - mynetwork

volumes:
    db_volume:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: "/home/efarin/data/db_volume"
    wp_volume:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: "/home/efarin/data/wp_volume"

networks:
    mynetwork: